### PR TITLE
Hiding first Csv row

### PR DESCRIPTION
**Pull request by Vladichik**

### CODE REVIEW

**Comment by Vladichik** [comment]
Screen Shot 2022-09-13 at 9 12 53

**Comment by Vladichik** [comment]
Adding the ability to hide first CSV row that contains columns indexes.

**Comment by coston** [comment]
@Vladichik currently multi-dimensional arrays are not supported. Adding an arg for hiding the first row is not ideal. What if we simply supported matrix data?

**Comment by coston** [comment]
Please note that a TS refactor has been merged since your last push.

**Pull request closed without merging**
